[versions]
ktor = "2.1.2"
datetime = "0.4.0"
serialization = "1.4.0"
kotlin = "1.7.20"
logback = "1.4.1"
node-plugin = "3.4.0"

[libraries]

ktor-client-cio        = { version.ref = "ktor", group = "io.ktor", name = "ktor-client-cio" }
ktor-client-auth       = { version.ref = "ktor", group = "io.ktor", name = "ktor-client-auth" }
ktor-client-websockets = { version.ref = "ktor", group = "io.ktor", name = "ktor-client-websockets" }

ktor-serialization-kotlinx-json = { version.ref = "ktor", group = "io.ktor", name = "ktor-serialization-kotlinx-json" }

ktor-server-tests = { version.ref = "ktor", group = "io.ktor", name = "ktor-server-tests" }
ktor-server-autoHeadResponse    = { version.ref = "ktor", group = "io.ktor", name = "ktor-server-auto-head-response" }
ktor-server-auth                = { version.ref = "ktor", group = "io.ktor", name = "ktor-server-auth" }
ktor-server-callLogging         = { version.ref = "ktor", group = "io.ktor", name = "ktor-server-call-logging" }
ktor-server-contentNegotiation  = { version.ref = "ktor", group = "io.ktor", name = "ktor-server-content-negotiation" }
ktor-server-core                = { version.ref = "ktor", group = "io.ktor", name = "ktor-server-core" }
ktor-server-cors                = { version.ref = "ktor", group = "io.ktor", name = "ktor-server-cors" }
ktor-server-defaultHeaders      = { version.ref = "ktor", group = "io.ktor", name = "ktor-server-default-headers" }
ktor-server-netty               = { version.ref = "ktor", group = "io.ktor", name = "ktor-server-netty" }
ktor-server-statusPages         = { version.ref = "ktor", group = "io.ktor", name = "ktor-server-status-pages" }
ktor-server-websockets          = { version.ref = "ktor", group = "io.ktor", name = "ktor-server-websockets" }



kotlinx-datetime = { version.ref = "datetime", group = "org.jetbrains.kotlinx", name = "kotlinx-datetime" }

kotlinx-serialization-json = { version.ref = "serialization", group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json" }

kotlin-serialization-plugin = { version.ref = "kotlin", group = "org.jetbrains.kotlin", name = "kotlin-serialization" }
kotlin-gradle-plugin        = { version.ref = "kotlin", group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin" }
kotlin-junit                = { version.ref = "kotlin", group = "org.jetbrains.kotlin", name = "kotlin-test-junit" }

logback = { version.ref = "logback", group = "ch.qos.logback", name = "logback-classic" }

[plugins]

ktor = { id = "io.ktor.plugin",  version.ref = "ktor" }
node = { id = "com.github.node-gradle.node", version.ref = "node-plugin" }