name: Lint overlay

on:
  push:
    paths:
      - src/frontend/overlay/**
  pull_request:
    paths:
      - src/frontend/overlay/**


jobs:
  lint:
    name: Lint overlay
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: 'src/frontend/package-lock.json'
      - name: "Install dependencies"
        run: npm ci
        working-directory: "src/frontend"
      - name: "Lint overlay js"
        working-directory: "src/frontend/overlay"
        run: npm run lint:js
      - name: "Lint overlay css"
        working-directory: "src/frontend/overlay"
        run: npm run lint:css
