name: Publish release on tag

on:
  push:
    tags:
      - 'v*'


jobs:
  build:
    name: Create artifacts from master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - uses: actions/setup-java@master
        with:
          distribution: adopt
          java-version: 17
          cache: 'gradle'

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: release --scan -Pnpm.download=false

      - uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: artifacts

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "${{ github.event.inputs.tagname }}"
          draft: true
          files: |
            artifacts/*.jar

