name: Publish release on tag

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: Name of release
        required: true


jobs:
  build:
    name: Create artifacts from master
    runs-on: ubuntu-latest
    steps:
      - name: Set VERSION variable from tag
        run: |
                  WORKFLOW_VERSION=${{ github.event.inputs.version }}
                  GIT_VERSION=${GITHUB_REF#refs/tags/}
                  if [ -z "${WORKFLOW_VERSION}" ] ; then 
                      echo "version=${GIT_VERSION:1}" >> $GITHUB_ENV
                  else 
                      echo "version=${WORKFLOW_VERSION}" >> $GITHUB_ENV
                  fi
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - uses: actions/setup-java@master
        with:
          distribution: adopt
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: release --scan -Pnpm.download=false -Pbuild_version=${{ env.version }} -i

      - uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: artifacts

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "v${{ github.event.inputs.version }}"
          draft: true
          files: |
            artifacts/*.jar

