name: Publish release on tag

on:
  push:
    tags:
      - 'v*'


jobs:
  build:
    name: Create artifacts from master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 17
        uses: actions/setup-java@master
        with:
          distribution: adopt
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew release

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: artifacts
          path: artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${GITHUB_REF#*/*/}
          release_name: Release ${GITHUB_REF#*/*/}
          draft: true
          prerelease: false

