name: Make a test release

on:
  workflow_dispatch:


jobs:
  build:
    name: Create artifacts from master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - uses: actions/setup-java@master
        with:
          distribution: adopt
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: release --scan -Pnpm.download=false -i

      - uses: actions/upload-artifact@master
        with:
          path: artifacts/*

